apiVersion: neosync.dev/v1alpha1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: job-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: job-sample
spec:
  # TODO(user): Add fields here
