apiVersion: neosync.dev/v1alpha1
kind: JobRun
metadata:
  labels:
    app.kubernetes.io/name: jobrun
    app.kubernetes.io/instance: jobrun-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: jobrun-sample
spec:
  # TODO(user): Add fields here
