on:
  pull_request:
    # paths:
    #   - backend/**.go
    #   - worker/**.go
    #   - cli/**.go

name: Golang Lint

jobs:
  resolve-modules:
    name: Resolve Go Modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - id: set-matrix
        run: ./hack/resolve-go-modules.sh
  golangci:
    name: Linter
    needs: resolve-modules
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: golangci
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          working-directory: ${{ matrix.workdir }}
